<?php
/**
 * BuyerInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BuyerInformationTest Class Doc Comment
 *
 * @category    Class
 * @description BuyerInformation
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BuyerInformationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BuyerInformation"
     */
    public function testBuyerInformation()
    {
    }

    /**
     * Test attribute "buyer_name"
     */
    public function testPropertyBuyerName()
    {
    }

    /**
     * Test attribute "buyer_email"
     */
    public function testPropertyBuyerEmail()
    {
    }

    /**
     * Test attribute "buyer_country"
     */
    public function testPropertyBuyerCountry()
    {
    }

    /**
     * Test attribute "buyer_zip"
     */
    public function testPropertyBuyerZip()
    {
    }

    /**
     * Test attribute "buyer_state"
     */
    public function testPropertyBuyerState()
    {
    }

    /**
     * Test attribute "buyer_city"
     */
    public function testPropertyBuyerCity()
    {
    }

    /**
     * Test attribute "buyer_address2"
     */
    public function testPropertyBuyerAddress2()
    {
    }

    /**
     * Test attribute "buyer_address1"
     */
    public function testPropertyBuyerAddress1()
    {
    }

    /**
     * Test attribute "buyer_phone"
     */
    public function testPropertyBuyerPhone()
    {
    }
}
