<?php
/**
 * ProductInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProductInformationTest Class Doc Comment
 *
 * @category    Class
 * @description ProductInformation
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductInformationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProductInformation"
     */
    public function testProductInformation()
    {
    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "pos_data"
     */
    public function testPropertyPosData()
    {
    }

    /**
     * Test attribute "item_desc"
     */
    public function testPropertyItemDesc()
    {
    }

    /**
     * Test attribute "item_code"
     */
    public function testPropertyItemCode()
    {
    }

    /**
     * Test attribute "physical"
     */
    public function testPropertyPhysical()
    {
    }

    /**
     * Test attribute "tax_included"
     */
    public function testPropertyTaxIncluded()
    {
    }
}
